language: android

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-27

    # emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26

